### ISSUE TITLE
Question regarding test example

### ISSUE THREAD

**Issue by janjaapbos** [ENQT-GmbH/remoc#2]
I have been experimenting howto create a persistent service.
See https://github.com/janjaapbos/remoc-test

I managed to achieve some results with this example.

In one terminal: cargo run --bin server_owner

In another terminal repeatedly: cargo run --bin client

Does this approach make sense at all? What would you advise for best practice?

_Originally posted by @janjaapbos in https://github.com/ENQT-GmbH/remoc/discussions/1#discussioncomment-1692799_

**Comment by surban** [comment]
Hi,

it does depend on what you want to achieve.  You send an `RwLock` to a client, which is then able to modify the data as desired. This may be useful, but for more complex tasks you might want to implement a remote API using the `rtc` module from Remoc.

Also you recreate the `Owner` of the `RwLock` for every connection, which does not make sense. You can clone `RwLock`s or obtain multiple `RwLock`s from the same owner.

Furthermore, currently your server can only handle one client at a time, since it is not accepting connection requests when a connection is established.

All of that should be easy to fix . I will have a look at your code tomorrow and modify it accordingly.

**Comment by surban** [comment]
I've made changes to your code at https://github.com/surban/remoc-test .

Particularly, I've moved the data types shared between the client and server into a shared library file to keep them consistent. Otherwise you might get send and receive errors if the data types become incompatible between client and server.

Furthermore, in Rust you should not include your transitive dependencies in `Cargo.toml`, so I've removed them.

There was a bug in Remoc that could potentially cause your code to stop working after the first connection to the server. I've fixed it in version 0.9.7.

**Comment by janjaapbos** [comment]
Super! Thank you very much for this. It is very helpful.
